inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'vendor/**/*'
    - 'public/**/*'
    - 'test/fixtures/**/*'
    - 'test/test_helper.rb'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'node_modules/**/*'
    - 'CONCILIACION_GUIDE.md'
    - 'README.md'
    - 'Dockerfile'